extend-exclude = ["apps/backend/rest_api/migrations"]
target-version = "py311"

[lint]
select = ["E4", "E7", "E9", "F", "I", "PD", "DJ"]

[format]
docstring-code-format = false

[lint.isort]
force-single-line = true
known-first-party = ["sonar_cli", "rest_api", "covsonar_backend"]
known-third-party = ["django", "tabulate", "line_profiler"]
case-sensitive = false
