extend-exclude = ["apps/backend/rest_api/migrations"]
target-version = "py311"

[lint]
select = ["E4", "E7", "E9", "F", "I"]

[format]
docstring-code-format = false

[lint.isort]
force-single-line = true
