# Generated by Django 4.2.8 on 2023-12-30 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0044_alter_mutation_gene_alter_mutation_replicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignment',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alignments', to='rest_api.sequence'),
        ),
    ]
