# Generated by Django 4.2.8 on 2024-01-10 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0045_alter_alignment_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignment2mutation',
            name='mutation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.mutation'),
        ),
        migrations.AlterField(
            model_name='mutation2annotation',
            name='alignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.alignment'),
        ),
        migrations.AlterField(
            model_name='sample2property',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.property'),
        ),
        migrations.AlterField(
            model_name='sample2property',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='rest_api.sample'),
        ),
    ]
