# Generated by Django 4.2.8 on 2024-01-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0046_alter_alignment2mutation_mutation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineages',
            name='parent_lineage',
        ),
        migrations.AddField(
            model_name='lineages',
            name='sublineage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
