# Generated by Django 4.2.8 on 2024-01-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0047_remove_lineages_parent_lineage_lineages_sublineage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample2property',
            name='value_float',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
