# Generated by Django 4.2.8 on 2024-01-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0048_alter_sample2property_value_float'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample2property',
            name='value_float',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
