# Generated by Django 4.2.8 on 2024-01-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0048_lineage_lineagealias_delete_lineages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='alt',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
