# Generated by Django 4.2.10 on 2024-03-11 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0049_alter_mutation_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.sequence'),
        ),
    ]
