# Generated by Django 4.2.10 on 2024-03-13 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0050_alter_sample_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NUL', 'Unknown'), ('SMP', 'Sample'), ('ANN', 'Annotation'), ('GBK', 'Genebank'), ('SAA', 'Sample Annotation Archive')], default='NUL', max_length=3)),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('file', models.CharField(max_length=400)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('success', models.BooleanField()),
                ('exception_text', models.TextField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'import_log',
            },
        ),
        migrations.DeleteModel(
            name='EnteredData',
        ),
        migrations.AlterField(
            model_name='sample',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.sequence'),
        ),
        migrations.AddConstraint(
            model_name='importlog',
            constraint=models.UniqueConstraint(fields=('type', 'name', 'updated'), name='unique_import_log'),
        ),
    ]
