# Generated by Django 4.2.10 on 2024-03-29 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "rest_api",
            "0051_importlog_delete_entereddata_alter_sample_sequence_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mutation2annotation",
            name="alignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rest_api.alignment"
            ),
        ),
        migrations.AlterField(
            model_name="mutation2annotation",
            name="annotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rest_api.annotationtype",
            ),
        ),
        migrations.AlterField(
            model_name="mutation2annotation",
            name="mutation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="rest_api.mutation"
            ),
        ),
    ]
