# Generated by Django 4.2.10 on 2024-04-26 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0052_alter_mutation2annotation_alignment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileProcessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "file_processing",
            },
        ),
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Q", "Queued"),
                            ("IP", "In Progress"),
                            ("C", "Completed"),
                            ("F", "Failed"),
                        ],
                        default="Q",
                        max_length=2,
                    ),
                ),
                ("entry_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "processing_job",
            },
        ),
        migrations.RemoveConstraint(
            model_name="importlog",
            name="unique_import_log",
        ),
        migrations.RemoveField(
            model_name="importlog",
            name="name",
        ),
        migrations.AddConstraint(
            model_name="importlog",
            constraint=models.UniqueConstraint(
                fields=("file", "updated"), name="unique_import_log"
            ),
        ),
        migrations.AddField(
            model_name="fileprocessing",
            name="processing_job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="rest_api.processingjob",
            ),
        ),
        migrations.AlterField(
            model_name="importlog",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rest_api.fileprocessing",
                to_field="file_name",
            ),
        ),
    ]
