# Generated by Django 4.2.10 on 2024-04-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0053_fileprocessing_processingjob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingjob",
            name="entry_time",
            field=models.DateTimeField(auto_now=True, unique=True),
        ),
        migrations.AlterField(
            model_name="processingjob",
            name="job_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
