# Generated by Django 4.2.10 on 2024-06-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0056_alter_mutation_alt_alter_mutation_ref"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sample",
            name="processing_date",
        ),
        migrations.AddField(
            model_name="sample",
            name="init_upload_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="last_update_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="mutation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ref__isnull", True)),
                fields=("alt", "start", "end", "type", "gene", "replicon"),
                name="unique_mutation_null_ref",
            ),
        ),
    ]
