# Generated by Django 4.2.10 on 2024-08-27 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0057_remove_sample_processing_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lineagealias",
            name="lineage",
        ),
        migrations.RemoveConstraint(
            model_name="lineage",
            name="unique_lineage",
        ),
        migrations.RemoveConstraint(
            model_name="lineage",
            name="unique_lineage_null_alias",
        ),
        migrations.RemoveField(
            model_name="lineage",
            name="lineage",
        ),
        migrations.RemoveField(
            model_name="lineage",
            name="prefixed_alias",
        ),
        migrations.AddField(
            model_name="lineage",
            name="name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lineage",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rest_api.lineage",
            ),
        ),
        migrations.AddConstraint(
            model_name="lineage",
            constraint=models.UniqueConstraint(
                fields=("name", "parent"), name="unique_lineage"
            ),
        ),
        migrations.DeleteModel(
            name="LineageAlias",
        ),
    ]
