# Generated by Django 4.2.10 on 2024-08-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0058_remove_lineagealias_lineage_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lineage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("name",),
                name="unique_lineage_parent_null",
            ),
        ),
    ]
