# Generated by Django 4.2.4 on 2023-11-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0035_mutation_unique_mutation_null_gene"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="alignment2mutation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="entereddata",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="mutation2annotation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="sample2property",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="alignment",
            constraint=models.UniqueConstraint(
                fields=("replicon", "sequence"), name="unique_alignment"
            ),
        ),
        migrations.AddConstraint(
            model_name="alignment2mutation",
            constraint=models.UniqueConstraint(
                fields=("mutation", "alignment"), name="unique_alignment2mutation"
            ),
        ),
        migrations.AddConstraint(
            model_name="annotationtype",
            constraint=models.UniqueConstraint(
                fields=("seq_ontology", "region", "impact"), name="unique_annotation"
            ),
        ),
        migrations.AddConstraint(
            model_name="entereddata",
            constraint=models.UniqueConstraint(
                fields=("type", "name"), name="unique_entered_data"
            ),
        ),
        migrations.AddConstraint(
            model_name="mutation2annotation",
            constraint=models.UniqueConstraint(
                fields=("mutation", "alignment", "annotation"),
                name="unique_mutation2annotation",
            ),
        ),
        migrations.AddConstraint(
            model_name="sample2property",
            constraint=models.UniqueConstraint(
                fields=("property", "sample"), name="unique_property2sample"
            ),
        ),
    ]
