# Generated by Django 4.2.4 on 2023-11-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0036_alter_alignment2mutation_unique_together_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="mutation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("alt__isnull", True)),
                fields=("ref", "start", "end", "type", "gene", "replicon"),
                name="unique_mutation_null_alt",
            ),
        ),
        migrations.AddConstraint(
            model_name="mutation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("alt__isnull", True), ("gene__isnull", True)),
                fields=("ref", "start", "end", "type", "replicon"),
                name="unique_mutation_null_alt_null_gene",
            ),
        ),
    ]
