# Generated by Django 4.2.4 on 2023-11-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0037_mutation_unique_mutation_null_alt_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="annotationtype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("region__isnull", True)),
                fields=("seq_ontology", "impact"),
                name="unique_annotation_null_region",
            ),
        ),
    ]
