# Generated by Django 4.1.13 on 2023-11-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0039_alter_gene_cds_accession_alter_gene_cds_symbol_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mutation",
            name="alt",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="mutation",
            name="ref",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
