# Generated by Django 4.1.13 on 2023-12-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0040_alter_mutation_alt_alter_mutation_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="translation_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
