# Generated by Django 4.1.13 on 2023-12-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0041_reference_translation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mutation",
            name="ref",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
