# Generated by Django 4.2.8 on 2023-12-23 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0042_alter_mutation_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignment',
            name='replicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.replicon'),
        ),
        migrations.AlterField(
            model_name='alignment2mutation',
            name='alignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.alignment'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='replicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.replicon'),
        ),
        migrations.AlterField(
            model_name='genesegment',
            name='gene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.gene'),
        ),
        migrations.AlterField(
            model_name='replicon',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.reference'),
        ),
    ]
