# Generated by Django 4.2.8 on 2024-01-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0046_alter_alignment2mutation_mutation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample2property',
            name='value_float',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
