# Generated by Django 4.2.10 on 2024-06-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0054_alter_processingjob_entry_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gene",
            name="gene_accession",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
