# Generated by Django 4.2.10 on 2024-06-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0055_alter_gene_gene_accession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mutation",
            name="alt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mutation",
            name="ref",
            field=models.TextField(blank=True, null=True),
        ),
    ]
