# Generated by Django 4.2.10 on 2024-09-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0059_lineage_unique_lineage_parent_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importlog",
            name="type",
            field=models.CharField(
                choices=[
                    ("NUL", "Unknown"),
                    ("SMP", "Sample"),
                    ("ANN", "Annotation"),
                    ("GBK", "Genebank"),
                    ("SAA", "Sample Annotation Archive"),
                    ("PTY", "Property"),
                ],
                default="NUL",
                max_length=3,
            ),
        ),
    ]
