# Generated by Django 4.2.10 on 2024-10-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0060_alter_importlog_type"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE INDEX collection_date_week_idx ON sample (EXTRACT(\'week\' FROM collection_date));"
        ),
        migrations.RunSQL(
            sql="CREATE INDEX collection_date_month_idx ON sample (EXTRACT(\'month\' FROM collection_date));"
        ),
        migrations.RunSQL(
            sql="CREATE INDEX collection_date_year_idx ON sample (EXTRACT(\'year\' FROM collection_date));"
        ),
    ]
