# Generated by Django 4.2.10 on 2024-11-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0061_auto_20241031_1135"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(fields=["name"], name="sample_name_be7a19_idx"),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(
                fields=["sequencing_tech"], name="sample_sequenc_99b417_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(fields=["country"], name="sample_country_da3900_idx"),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(fields=["host"], name="sample_host_ef80b0_idx"),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(fields=["zip_code"], name="sample_zip_cod_2b199b_idx"),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(fields=["lab"], name="sample_lab_f9c2e2_idx"),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(fields=["lineage"], name="sample_lineage_1bf41c_idx"),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(
                fields=["genome_completeness"], name="sample_genome__ca4dc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(
                fields=["collection_date"], name="sample_collect_861c47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(
                fields=["init_upload_date"], name="sample_init_up_6bdf99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(
                fields=["last_update_date"], name="sample_last_up_5f4e06_idx"
            ),
        ),
    ]
