# Generated by Django 4.2.10 on 2024-12-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0062_sample_sample_name_be7a19_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mutation",
            name="parent_id",
        ),
        migrations.AddField(
            model_name="mutation",
            name="parent",
            field=models.ManyToManyField(to="rest_api.mutation"),
        ),
    ]
