# Generated by Django 4.2.10 on 2024-12-04 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0062_sample_sample_name_be7a19_idx_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mutation2annotation",
            name="unique_mutation2annotation",
        ),
        migrations.RemoveField(
            model_name="mutation2annotation",
            name="alignment",
        ),
        migrations.AddField(
            model_name="annotationtype",
            name="mutations",
            field=models.ManyToManyField(
                related_name="annotations",
                through="rest_api.Mutation2Annotation",
                to="rest_api.mutation",
            ),
        ),
        migrations.AlterField(
            model_name="alignment",
            name="replicon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rest_api.replicon"
            ),
        ),
        migrations.AlterField(
            model_name="alignment",
            name="sequence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alignments",
                to="rest_api.sequence",
            ),
        ),
        migrations.AlterField(
            model_name="annotationtype",
            name="impact",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="annotationtype",
            name="seq_ontology",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="gene",
            name="end",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="gene",
            name="gene_sequence",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="gene",
            name="replicon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rest_api.replicon"
            ),
        ),
        migrations.AlterField(
            model_name="gene",
            name="start",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="gene",
            name="strand",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="genesegment",
            name="gene",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rest_api.gene"
            ),
        ),
        migrations.AlterField(
            model_name="mutation",
            name="end",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="mutation",
            name="replicon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rest_api.replicon"
            ),
        ),
        migrations.AlterField(
            model_name="mutation",
            name="start",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="mutation2annotation",
            name="annotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rest_api.annotationtype",
            ),
        ),
        migrations.AlterField(
            model_name="mutation2annotation",
            name="mutation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rest_api.mutation"
            ),
        ),
        migrations.AlterField(
            model_name="replicon",
            name="reference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rest_api.reference"
            ),
        ),
        migrations.AlterField(
            model_name="replicon",
            name="sequence",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="sample",
            name="datahash",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="sample",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="sample",
            name="sequence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="rest_api.sequence"
            ),
        ),
        migrations.AddIndex(
            model_name="mutation2annotation",
            index=models.Index(
                fields=["annotation", "mutation"], name="mutation2an_annotat_6c71ff_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mutation2annotation",
            constraint=models.UniqueConstraint(
                fields=("mutation", "annotation"), name="unique_mutation2annotation"
            ),
        ),
    ]
