# Generated by Django 4.2.10 on 2024-12-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rest_api",
            "0063_remove_mutation2annotation_unique_mutation2annotation_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotationtype",
            name="mutations",
        ),
        migrations.AddField(
            model_name="annotationtype",
            name="mutations",
            field=models.ManyToManyField(
                related_name="annotations", to="rest_api.mutation"
            ),
        ),
        migrations.DeleteModel(
            name="Mutation2Annotation",
        ),
    ]
