# Generated by Django 4.2.10 on 2024-12-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0064_alter_annotationtype_mutations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gene",
            name="gene_sequence",
            field=models.TextField(blank=True, null=True),
        ),
    ]
