# Generated by Django 5.1.4 on 2024-12-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0064_remove_mutation_alignments_remove_mutation_gene_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="nucleotidemutation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ref__isnull", True), ("alt__isnull", True)),
                fields=("start", "end", "replicon"),
                name="unique_nt_mutation_null_alt_null_ref",
            ),
        ),
    ]
