# Generated by Django 5.1.4 on 2024-12-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0065_nucleotidemutation_unique_nt_mutation_null_alt_null_ref"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="nucleotidemutation",
            name="unique_nt_mutation_null_alt",
        ),
        migrations.RemoveConstraint(
            model_name="nucleotidemutation",
            name="unique_nt_mutation_null_ref",
        ),
        migrations.RemoveConstraint(
            model_name="nucleotidemutation",
            name="unique_nt_mutation_null_alt_null_ref",
        ),
        migrations.AlterField(
            model_name="nucleotidemutation",
            name="alt",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="nucleotidemutation",
            name="ref",
            field=models.TextField(),
        ),
    ]
