# Generated by Django 5.1.7 on 2025-03-19 13:28

import django.db.models.deletion
from django.db import migrations, models

def update_amino_acid_cds(apps, schema_editor):
    AminoAcidMutation = apps.get_model("rest_api", "AminoAcidMutation")
    CDS = apps.get_model("rest_api", "CDS")
    for mutation in AminoAcidMutation.objects.prefetch_related("gene"):
        cds = CDS.objects.get_or_create(gene_id=mutation.gene_id)[0]
        mutation.cds_id = cds.id
        mutation.save()

class Migration(migrations.Migration):

    dependencies = [
        (
            "rest_api",
            "0067_remove_aminoacidmutation_unique_aa_mutation_null_gene_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CDS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accession",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("sequence", models.TextField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "cds",
            },
        ),
        migrations.CreateModel(
            name="CDSSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.BigIntegerField()),
                ("start", models.BigIntegerField()),
                ("end", models.BigIntegerField()),
                ("forward_strand", models.BooleanField()),
            ],
            options={
                "db_table": "cds_part",
            },
        ),
        migrations.CreateModel(
            name="Peptide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mat_peptide", "Mat Peptide"),
                            ("sig_peptide", "Sig Peptide"),
                        ]
                    ),
                ),
            ],
            options={
                "db_table": "peptide",
            },
        ),
        migrations.CreateModel(
            name="PeptideSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.BigIntegerField()),
                ("start", models.BigIntegerField()),
                ("end", models.BigIntegerField()),
            ],
            options={
                "db_table": "peptide_part",
            },
        ),
        migrations.RemoveConstraint(
            model_name="aminoacidmutation",
            name="unique_aa_mutation",
        ),
        migrations.RemoveIndex(
            model_name="aminoacidmutation",
            name="amino_acid__gene_id_d4203e_idx",
        ),
        migrations.RenameField(
            model_name="gene",
            old_name="gene_accession",
            new_name="accession",
        ),
        migrations.RenameField(
            model_name="gene",
            old_name="cds_sequence",
            new_name="sequence",
        ),
        migrations.RenameField(
            model_name="gene",
            old_name="cds_symbol",
            new_name="symbol",
        ),
        migrations.RenameField(
            model_name="genesegment",
            old_name="segment",
            new_name="order",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="standard",
            new_name="default",
        ),
        migrations.RemoveField(
            model_name="aminoacidmutation",
            name="replicon",
        ),
        migrations.RemoveField(
            model_name="gene",
            name="cds_accession",
        ),
        migrations.RemoveField(
            model_name="gene",
            name="gene_sequence",
        ),
        migrations.RemoveField(
            model_name="gene",
            name="gene_symbol",
        ),
        migrations.RemoveField(
            model_name="gene",
            name="strand",
        ),
        migrations.RemoveField(
            model_name="genesegment",
            name="base",
        ),
        migrations.RemoveField(
            model_name="genesegment",
            name="strand",
        ),
        migrations.RemoveField(
            model_name="property",
            name="target",
        ),
        migrations.AddField(
            model_name="gene",
            name="forward_strand",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gene",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CDS", "Cds"),
                    ("rRNA", "Rrna"),
                    ("tRNA", "Trna"),
                    ("ncRNA", "Ncrna"),
                    ("miRNA", "Mirna"),
                    ("misc_RNA", "Misc Rna"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="genesegment",
            name="forward_strand",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sample",
            name="data_set",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(fields=["data_set"], name="sample_data_se_2b6d8f_idx"),
        ),
        migrations.AddConstraint(
            model_name="genesegment",
            constraint=models.UniqueConstraint(
                fields=("gene", "order"), name="unique_gene_segment"
            ),
        ),
        migrations.AddField(
            model_name="cds",
            name="gene",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rest_api.gene"
            ),
        ),
        migrations.AddField(
            model_name="aminoacidmutation",
            name="cds",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rest_api.cds",
                null=True
            ),
            preserve_default=False,
        ),
        migrations.RunPython(update_amino_acid_cds),
        migrations.AlterField(
            model_name="aminoacidmutation",
            name="cds",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rest_api.cds"
            ),
        ),
        migrations.RemoveField(
            model_name="aminoacidmutation",
            name="gene",
        ),
        migrations.AddIndex(
            model_name="aminoacidmutation",
            index=models.Index(fields=["cds"], name="amino_acid__cds_id_9e03a3_idx"),
        ),
        migrations.AddConstraint(
            model_name="aminoacidmutation",
            constraint=models.UniqueConstraint(
                fields=("ref", "alt", "start", "end", "cds"), name="unique_aa_mutation"
            ),
        ),
        migrations.AddField(
            model_name="cdssegment",
            name="cds",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rest_api.cds"
            ),
        ),
        migrations.AddField(
            model_name="peptide",
            name="cds",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rest_api.cds"
            ),
        ),
        migrations.AddField(
            model_name="peptidesegment",
            name="peptide",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rest_api.peptide"
            ),
        ),
        migrations.AddConstraint(
            model_name="cdssegment",
            constraint=models.UniqueConstraint(
                fields=("cds", "order"), name="unique_cds_part"
            ),
        ),
        migrations.AddConstraint(
            model_name="peptidesegment",
            constraint=models.UniqueConstraint(
                fields=("peptide", "order"), name="unique_peptide_part"
            ),
        ),
    ]
