# Generated by Django 5.1.7 on 2025-05-02 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0069_remove_cdssegment_unique_cds_part_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aminoacidmutation",
            name="is_frameshift",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="peptidesegment",
            name="end_cds",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="peptidesegment",
            name="start_cds",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cdssegment",
            name="cds",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cds_segments",
                to="rest_api.cds",
            ),
        ),
        migrations.AlterField(
            model_name="peptide",
            name="cds",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="peptides",
                to="rest_api.cds",
            ),
        ),
        migrations.AlterField(
            model_name="peptidesegment",
            name="peptide",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="peptide_segments",
                to="rest_api.peptide",
            ),
        ),
        migrations.AlterModelTable(
            name="peptidesegment",
            table="peptide_segment",
        ),
    ]
