# Generated by Django 5.1.7 on 2025-03-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0069_remove_cdssegment_unique_cds_part_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="name",
            field=models.CharField(blank=True, max_length=600, null=True, unique=True),
        ),
    ]
