# Generated by Django 5.1.7 on 2025-06-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0071_alter_reference_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aminoacidmutation",
            name="is_frameshift",
        ),
        migrations.AddField(
            model_name="nucleotidemutation",
            name="is_frameshift",
            field=models.BooleanField(default=False),
        ),
    ]
