# Generated by Django 5.1.7 on 2025-07-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0072_remove_aminoacidmutation_is_frameshift_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cds",
            name="description",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
