# Generated by Django 5.1.7 on 2025-09-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0072_remove_aminoacidmutation_is_frameshift_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sample",
            name="length",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="sequence",
        ),
        migrations.AddField(
            model_name="sample",
            name="sequences",
            field=models.ManyToManyField(
                related_name="samples", to="rest_api.sequence"
            ),
        ),
        migrations.AddField(
            model_name="sequence",
            name="init_upload_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="sequence",
            name="last_update_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sequence",
            name="length",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sequence",
            name="name",
            field=models.CharField(default="sd", max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="sequence",
            index=models.Index(fields=["name"], name="sequence_name_455b90_idx"),
        ),
        migrations.AddIndex(
            model_name="sequence",
            index=models.Index(
                fields=["init_upload_date"], name="sequence_init_up_dd7d45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sequence",
            index=models.Index(
                fields=["last_update_date"], name="sequence_last_up_f215ac_idx"
            ),
        ),
    ]
