# Generated by Django 5.1.7 on 2025-09-19 13:13

from django.db import migrations, models
from django.utils import timezone


def _unique_sequence_name(base_name, used_names, sequence_pk):
    base_name = (base_name or f"sequence-{sequence_pk}").strip()
    if not base_name:
        base_name = f"sequence-{sequence_pk}"

    candidate = base_name[:200]
    if candidate not in used_names:
        used_names.add(candidate)
        return candidate

    prefix = base_name[:190] or "sequence"
    suffix = 1
    while True:
        candidate = f"{prefix}-{suffix}"[:200]
        if candidate not in used_names:
            used_names.add(candidate)
            return candidate
        suffix += 1


def backfill_sequence_metadata(apps, schema_editor):
    Sample = apps.get_model("rest_api", "Sample")
    Sequence = apps.get_model("rest_api", "Sequence")
    SampleSequence = Sample.sequences.through
    db_alias = schema_editor.connection.alias

    used_names = set(
        Sequence.objects.using(db_alias)
        .exclude(name__isnull=True)
        .exclude(name="")
        .values_list("name", flat=True)
    )
    now = timezone.now()

    through_rows = []
    for sequence in Sequence.objects.using(db_alias).all().iterator():
        samples = list(
            Sample.objects.using(db_alias).filter(sequence_id=sequence.pk).order_by("id")
        )

        preferred_name = next(
            (sample.name for sample in samples if sample.name and sample.name.strip()),
            None,
        )
        sequence.name = _unique_sequence_name(
            preferred_name or sequence.seqhash,
            used_names,
            sequence.pk,
        )

        if sequence.length is None:
            sequence.length = next(
                (sample.length for sample in samples if sample.length is not None),
                None,
            )

        sequence.init_upload_date = min(
            (sample.init_upload_date for sample in samples if sample.init_upload_date),
            default=now,
        )
        sequence.last_update_date = max(
            (sample.last_update_date for sample in samples if sample.last_update_date),
            default=None,
        )
        sequence.save(
            update_fields=[
                "name",
                "length",
                "init_upload_date",
                "last_update_date",
            ]
        )

        for sample in samples:
            through_rows.append(
                SampleSequence(sample_id=sample.pk, sequence_id=sequence.pk)
            )

    if through_rows:
        SampleSequence.objects.using(db_alias).bulk_create(through_rows)


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0072_remove_aminoacidmutation_is_frameshift_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="sequences",
            field=models.ManyToManyField(
                related_name="samples", to="rest_api.sequence"
            ),
        ),
        migrations.AddField(
            model_name="sequence",
            name="init_upload_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sequence",
            name="last_update_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sequence",
            name="length",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sequence",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RunPython(backfill_sequence_metadata, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="sample",
            name="length",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="sequence",
        ),
        migrations.AlterField(
            model_name="sequence",
            name="init_upload_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name="sequence",
            index=models.Index(fields=["name"], name="sequence_name_455b90_idx"),
        ),
        migrations.AddIndex(
            model_name="sequence",
            index=models.Index(
                fields=["init_upload_date"], name="sequence_init_up_dd7d45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sequence",
            index=models.Index(
                fields=["last_update_date"], name="sequence_last_up_f215ac_idx"
            ),
        ),
    ]
