# Generated by Django 5.1.7 on 2025-09-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0073_remove_sample_length_remove_sample_sequence_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequence",
            name="seqhash",
            field=models.CharField(max_length=200),
        ),
    ]
