# Generated by Django 5.1.7 on 2025-11-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0074_alter_sequence_seqhash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cds",
            name="accession",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="gene",
            name="accession",
            field=models.CharField(default="acc", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reference",
            name="accession",
            field=models.CharField(default="acc", max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reference",
            name="organism",
            field=models.CharField(default="sample_organism", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="replicon",
            name="accession",
            field=models.CharField(default="acc", max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
