# Generated by Django 5.1.14 on 2025-11-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0075_alter_cds_accession_alter_gene_accession_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gene",
            name="locus_tag",
        ),
        migrations.AlterField(
            model_name="gene",
            name="accession",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="gene",
            name="symbol",
            field=models.CharField(default="symbol", max_length=50),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="gene",
            constraint=models.UniqueConstraint(
                fields=("replicon", "accession"), name="unique_accession_per_replicon"
            ),
        ),
    ]
