# Generated by Django 5.2.8 on 2026-02-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0076_remove_gene_locus_tag_alter_gene_accession_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="nucleotidemutation",
            index=models.Index(fields=["start", "end"], name="idx_nt_mut_start_end"),
        ),
        migrations.AddIndex(
            model_name="nucleotidemutation",
            index=models.Index(fields=["ref", "alt"], name="idx_nt_mut_ref_alt"),
        ),
        migrations.AddIndex(
            model_name="nucleotidemutation",
            index=models.Index(
                fields=["end", "ref", "alt"], name="idx_nt_mut_end_ref_alt"
            ),
        ),
        migrations.AddIndex(
            model_name="nucleotidemutation",
            index=models.Index(
                fields=["alt", "end", "start"], name="idx_nt_mut_alt_end_start"
            ),
        ),
        migrations.AddIndex(
            model_name="nucleotidemutation",
            index=models.Index(
                fields=["alt", "end", "ref"], name="idx_nt_mut_alt_end_ref"
            ),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(
                fields=["lineage", "collection_date"], name="idx_sample_lineage_date"
            ),
        ),
        migrations.AddIndex(
            model_name="sample2property",
            index=models.Index(
                fields=["sample", "property"], name="idx_s2p_sample_property"
            ),
        ),
        migrations.AddIndex(
            model_name="sample2property",
            index=models.Index(
                fields=["property", "value_varchar"], name="idx_s2p_prop_varchar"
            ),
        ),
        migrations.AddIndex(
            model_name="sample2property",
            index=models.Index(
                fields=["property", "value_integer"], name="idx_s2p_prop_integer"
            ),
        ),
        migrations.AddIndex(
            model_name="sample2property",
            index=models.Index(
                fields=["property", "value_date"], name="idx_s2p_prop_date"
            ),
        ),
        migrations.AddIndex(
            model_name="sample2property",
            index=models.Index(
                fields=["property", "value_float"], name="idx_s2p_prop_float"
            ),
        ),
    ]
