# Generated by Django 5.2.14 on 2026-06-11 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0076_remove_gene_locus_tag_alter_gene_accession_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lineage",
            name="unique_lineage",
        ),
        migrations.RemoveConstraint(
            model_name="lineage",
            name="unique_lineage_parent_null",
        ),
        migrations.AddField(
            model_name="lineage",
            name="reference",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rest_api.reference",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="lineage",
            constraint=models.UniqueConstraint(
                fields=("name", "parent", "reference"), name="unique_lineage"
            ),
        ),
        migrations.AddConstraint(
            model_name="lineage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("name", "reference"),
                name="unique_lineage_parent_null",
            ),
        ),
    ]
