name: backend test

on:
  push:
    paths:
      - './apps/backend/**'
  workflow_dispatch:

permissions: write-all

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      COMPOSE_ARGS: "-f compose.yml -f compose-dev.yml --env-file conf/docker/common.env --env-file conf/docker/dev.env --env-file conf/docker/dev-secrets.env"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/backend
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Build the backend container
        run: |
          docker build -t backend:local -f Dockerfile .

      - name: Bring up containers
        run: docker compose $COMPOSE_ARGS up --detach --quiet-pull

      - name: Install testing dependencies
        run: docker compose $COMPOSE_ARGS exec -t sonar-django-backend pip install --no-cache-dir --disable-pip-version-check -r requirements-testing.txt
          
      - name: Run tests
        run: docker compose $COMPOSE_ARGS exec -T sonar-django-backend coverage run ./manage.py test --no-input

