name: frontend test build
on:
  pull_request:
    paths:
      - 'apps/frontend/**'
  workflow_dispatch:
jobs:
  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/frontend
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Install
        run: npm ci
      - name: Run eslint
        run: npm run lint
      - name: Run prettier
        run: npm run format-check
      - name: Do type checks
        run: npm run type-check
