name: Run tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Build the backend container
        run: |
          cp template.env .env
          docker build -t backend_dev:local -f Dockerfile .

      - name: Bring up containers
        run: docker compose -f docker-compose-dev.yml up --detach --quiet-pull

      - name: Install testing dependencies
        run: docker compose -f docker-compose-dev.yml exec -t dev-django pip install --no-cache-dir --disable-pip-version-check -r requirements-testing.txt
          
      - name: Run tests
        run: docker compose -f docker-compose-dev.yml exec -T dev-django coverage run ./manage.py test --no-input

      - name: Generate reports
        run: docker compose -f docker-compose-dev.yml exec -T dev-django coverage xml

      - uses: jwalton/gh-find-current-pr@v1
        id: finder

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.4
        with:
          reports: 'coverage.xml'
          targetdir: 'coveragereport'
          reporttypes: 'HtmlInline;Cobertura;MarkdownSummary' 

      - name: Publish coverage summary
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ steps.finder.outputs.pr }}
          path: coveragereport/Summary.md
